In [2]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [3]:
import pandas as pd
from pathlib import Path
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
plt.rcParams.update({'font.size': 22})

In [5]:
folder = Path("../../../Slides")

In [43]:
cat_train = ["BAL_Cat_Turnbull blue_1.svs", 
                         "BAL_Cat_Turnbull blue_6.svs", 
                         "BAL_Cat_Turnbull blue_14.svs", 
                         "BAL_Cat_Turnbull blue_13.svs", 
                         "BAL_Cat_Turnbull blue_2.svs", ]
cat_val = ["BAL_Cat_Turnbull blue_12.svs", "BAL_Cat_Turnbull blue_10.svs"]



equine_train = ["15_EIPH_568320 berliner blau.svs", 
                         "22_EIPH_575216 Berliner Blau.svs", 
                         "30_EIPH_588355 Berliner Blau.svs", 
                         "19_EIPH_566933 L Tunrbull blue.svs", 
                         "02_EIPH_574162 Turnbull blue-001.svs", 
                        ]
equine_val = ["27_EIPH_571557 Turnbull blue.svs", "17_EIPH_575796 Berliner Blau.svs"]



human_train = ["2707_20 TB BAL Human neu.svs", 
                         "11480_19 humane BAL Berliner Blau.svs", 
                         "10080_19 humane BAL Berliner Blau-001.svs", 
                         "10052_19 humane BAL Berliner Blau-001.svs", 
                         "10120_19 humane BAL Berliner Blau.svs" 
                        ]
human_val = ["10227_19 humane BAL Berliner Blau.svs", "2702_20 BB Human BAL-001.svs"]

In [14]:
grade_list = [0, 1]
annotations_path = Path("../EIPH_Screening_Annotations.pkl")
annotations = pd.read_pickle(annotations_path)

#annotations = annotations[annotations["grade"].isin(grade_list)]
annotations.head()

,id,image_id,image_set,species,image_name,image_type,grade,vector,unique_identifier,user_id,deleted,last_editor,data_set_name,version
0,1049539,3512,222,Cat,BAL_Cat_Turnbull blue_1.svs,Turnbull,0,"{'x1': 9903.0, 'x2': 10029.0, 'y1': 5508.0, 'y...",875aab61-3f1f-429a-a053-f87aba6c99da,1,False,1,SDATA,Screened
1,1049548,3512,222,Cat,BAL_Cat_Turnbull blue_1.svs,Turnbull,0,"{'x1': 12243.0, 'x2': 12375.0, 'y1': 14740.0, ...",d718f087-7a46-4e22-8610-ba5f82d04818,1,False,1,SDATA,Screened
2,1049551,3512,222,Cat,BAL_Cat_Turnbull blue_1.svs,Turnbull,0,"{'x1': 20253.0, 'x2': 20366.0, 'y1': 4149.0, '...",7e9cc21f-4a51-4d12-99dd-daffa3e6f368,1,False,1,SDATA,Screened
3,1049568,3512,222,Cat,BAL_Cat_Turnbull blue_1.svs,Turnbull,0,"{'x1': 2906.0, 'x2': 3030.0, 'y1': 16767.0, 'y...",0a546034-021b-4739-82bf-b09c7a5226d5,1,False,1,SDATA,Screened
4,1049624,3512,222,Cat,BAL_Cat_Turnbull blue_1.svs,Turnbull,0,"{'x1': 11203.0, 'x2': 11328.0, 'y1': 7867.0, '...",52536c1e-32f3-4a15-9c08-0350c0ad1b2b,1,False,1,SDATA,Screened

In [39]:
data = []

for image_name in annotations["image_name"].unique():
    
    frame = annotations[annotations["image_name"] == image_name]
    
    _0 = frame[frame["grade"] == 0].shape[0]
    _1 = frame[frame["grade"] == 1].shape[0]
    _2 = frame[frame["grade"] == 2].shape[0]
    _3 = frame[frame["grade"] == 3].shape[0]
    _4 = frame[frame["grade"] == 4].shape[0]
    species = frame["species"].unique()[0]
    
    mean = frame[(frame["grade"] == 0) | (frame["grade"] == 1)]["grade"].mean()
    mean_abs = abs(0.5 - mean)
                                                                
    
    #set_type = "Val"
    #if image_name in cat_train+equine_train+human_train:
    #    set_type = "Train"
        
    data.append([image_name, species, _0, _1, _2, _3, _4, set_type, mean, mean_abs])
    
data = pd.DataFrame(data, columns=["image_name", "Species", "0", "1", "2", "3", "4", "Type", "mean", "mean_abs"]).sort_values(by=["Type", "Species"]) 
data

,image_name,Species,0,1,2,3,4,Type,mean,mean_abs
0,BAL_Cat_Turnbull blue_1.svs,Cat,1200,2287,22,1,1,Val,0.655865,0.155865
1,BAL_Cat_Turnbull blue_2.svs,Cat,57,502,10,0,0,Val,0.898032,0.398032
2,BAL_Cat_Turnbull blue_6.svs,Cat,3009,895,0,0,0,Val,0.229252,0.270748
3,BAL_Cat_Turnbull blue_10.svs,Cat,412,371,4,1,0,Val,0.473819,0.026181
4,BAL_Cat_Turnbull blue_12.svs,Cat,1897,1387,1,0,0,Val,0.422351,0.077649
...,...,...,...,...,...,...,...,...,...,...
71,09_EIPH_563417 L Turnbull blue.svs,equine,269,286,158,3,0,Val,0.515315,0.015315
72,14_EIPH_568381 Turnbull blue.svs,equine,358,762,657,1291,692,Val,0.680357,0.180357
73,22_EIPH_575216 Turnbull blue.svs,equine,1119,2166,1496,828,2,Val,0.659361,0.159361
74,28_EIPH_569948 L Turnbull blue.svs,equine,747,302,41,0,0,Val,0.287893,0.212107
75,29_EIPH_566481 L Turnbull blue.svs,equine,598,251,69,7,1,Val,0.295642,0.204358

# Cat

In [40]:
cat = data[data["Species"]=="Cat"]
cat.sort_values(by=["mean_abs"])

,image_name,Species,0,1,2,3,4,Type,mean,mean_abs
3,BAL_Cat_Turnbull blue_10.svs,Cat,412,371,4,1,0,Val,0.473819,0.026181
4,BAL_Cat_Turnbull blue_12.svs,Cat,1897,1387,1,0,0,Val,0.422351,0.077649
0,BAL_Cat_Turnbull blue_1.svs,Cat,1200,2287,22,1,1,Val,0.655865,0.155865
2,BAL_Cat_Turnbull blue_6.svs,Cat,3009,895,0,0,0,Val,0.229252,0.270748
6,BAL_Cat_Turnbull blue_14.svs,Cat,2393,495,2,0,0,Val,0.171399,0.328601
5,BAL_Cat_Turnbull blue_13.svs,Cat,4663,810,2,0,0,Val,0.147999,0.352001
1,BAL_Cat_Turnbull blue_2.svs,Cat,57,502,10,0,0,Val,0.898032,0.398032

## Equine

In [41]:
cat = data[data["Species"]=="equine"]
cat.sort_values(by=["mean_abs"])

,image_name,Species,0,1,2,3,4,Type,mean,mean_abs
56,27_EIPH_571557 Turnbull blue.svs,equine,1392,1359,364,93,1,Val,0.494002,0.005998
27,17_EIPH_575796 Berliner Blau.svs,equine,2725,2625,715,166,14,Val,0.490654,0.009346
71,09_EIPH_563417 L Turnbull blue.svs,equine,269,286,158,3,0,Val,0.515315,0.015315
65,27_EIPH_571557 berliner blau.svs,equine,2213,2070,377,24,0,Val,0.483306,0.016694
25,15_EIPH_568320 berliner blau.svs,equine,2884,3124,2138,733,12,Val,0.519973,0.019973
30,22_EIPH_575216 Berliner Blau.svs,equine,2147,2441,2025,899,69,Val,0.532040,0.032040
36,30_EIPH_588355 Berliner Blau.svs,equine,2815,2464,1523,606,26,Val,0.466755,0.033245
22,10_EIPH_563417 R Berliner Blau.svs,equine,456,394,92,0,1,Val,0.463529,0.036471
49,19_EIPH_566933 L Tunrbull blue.svs,equine,1197,1012,316,36,0,Val,0.458126,0.041874
38,02_EIPH_574162 Turnbull blue-001.svs,equine,2094,2560,1291,364,2,Val,0.550064,0.050064
47,17_EIPH_575796 Turnbull blue.svs,equine,1641,2016,727,199,7,Val,0.551272,0.051272
68,20_EIPH_576150 berliner blau.svs,equine,1535,1902,818,337,17,Val,0.553390,0.053390
26,16_EIPH_574882 R Berliner Blau.svs,equine,537,705,303,152,25,Val,0.567633,0.067633
23,13_EIPH_570370 Berliner Blau.svs,equine,2478,1817,584,58,5,Val,0.423050,0.076950
46,16_EIPH_576172 Turnbull blue-002.svs,equine,313,444,252,51,2,Val,0.586526,0.086526
21,09_EIPH_563417 L berliner blau.svs,equine,554,389,107,5,0,Val,0.412513,0.087487
48,18_EIPH_574882 Turnbull blue-002.svs,equine,2904,2034,944,196,12,Val,0.411908,0.088092
61,02_EIPH_574162 berliner blau.svs,equine,3101,4527,1257,58,11,Val,0.593471,0.093471
50,20_EIPH_576150 Turnbull blue.svs,equine,1930,3000,1940,1021,0,Val,0.608519,0.108519
64,04_EIPH_567017 Berliner Blau.svs,equine,1150,1822,458,9,0,Val,0.613055,0.113055
31,23_EIPH_563476 Berliner Blau-001.svs,equine,1790,2916,2374,1259,203,Val,0.619635,0.119635
44,13_EIPH_570370 Turnbull blue-001.svs,equine,1229,2017,679,98,1,Val,0.621380,0.121380
42,10_EIPH_563417 R Turnbull blue-002.svs,equine,169,288,135,4,0,Val,0.630197,0.130197
57,30_EIPH_568355 Turnbull blue.svs,equine,1245,2156,1234,586,4,Val,0.633931,0.133931
41,05_EIPH_569923 Turnbull blue.svs,equine,967,554,104,9,0,Val,0.364234,0.135766
69,07_EIPH_574882 left lung Turnbull blue.svs,equine,1549,883,139,2,0,Val,0.363076,0.136924
58,31_EIPH_568354 Turnbull blue.svs,equine,2488,1409,72,16,1,Val,0.361560,0.138440
28,18_EIPH_574882 R Berliner Blau.svs,equine,4946,2797,797,59,8,Val,0.361229,0.138771
24,14_EIPH_568381 berliner blau-001.svs,equine,734,1383,1157,1436,461,Val,0.653283,0.153283
33,25_EIPH_568150 Berliner Blau.svs,equine,660,1269,1952,341,29,Val,0.657854,0.157854
73,22_EIPH_575216 Turnbull blue.svs,equine,1119,2166,1496,828,2,Val,0.659361,0.159361
67,03_EIPH_566933 R Berliner Blau neu.svs,equine,3403,1664,324,3,0,Val,0.328399,0.171601
66,01_EIPH_563479 Berliner Blau.svs,equine,716,1481,1112,339,76,Val,0.674101,0.174101
29,19_EIPH_566933 L Berliner Blau.svs,equine,2056,969,180,4,2,Val,0.320331,0.179669
72,14_EIPH_568381 Turnbull blue.svs,equine,358,762,657,1291,692,Val,0.680357,0.180357
63,31_EIPH_568354 Berliner Blau.svs,equine,1254,584,30,4,0,Val,0.317737,0.182263
20,08_EIPH_574999 Berliner Blau.svs,equine,182,394,615,393,35,Val,0.684028,0.184028
59,05_EIPH_569923 Berliner Blau.svs,equine,1298,587,97,2,0,Val,0.311406,0.188594
40,04_EIPH_567017 Turnbull blue-001.svs,equine,876,1977,1270,305,1,Val,0.692955,0.192955
39,03_EIPH_566933 R Turnbull blue.svs,equine,3323,1424,583,61,0,Val,0.299979,0.200021
45,15_EIPH_568320 Turnbull blue.svs,equine,935,2223,1674,1038,9,Val,0.703927,0.203927
75,29_EIPH_566481 L Turnbull blue.svs,equine,598,251,69,7,1,Val,0.295642,0.204358
74,28_EIPH_569948 L Turnbull blue.svs,equine,747,302,41,0,0,Val,0.287893,0.212107
37,01_EIPH_563479 Turnbull blue.svs,equine,536,1577,1837,658,5,Val,0.746332,0.246332
52,23_EIPH_563476 Turnbull blue.svs,equine,828,2461,2384,980,8,Val,0.748252,0.248252
54,25_EIPH_568150 Turnbull blue.svs,equine,255,777,1564,211,0,Val,0.752907,0.252907
19,07_EIPH_574882 Berliner Blau-001.svs,equine,1940,635,30,0,0,Val,0.246602,0.253398
35,29_EIPH_566481 L Berliner Blau.svs,equine,908,287,61,0,0,Val,0.240167,0.259833
32,24_EIPH_576255 Berliner Blau.svs,equine,639,2657,2772,476,46,Val,0.806129,0.306129
60,11_EIPH_575697 Berliner Blau.svs,equine,100,445,743,126,12,Val,0.816514,0.316514
70,08_EIPH_574999 R Turnbull blue.svs,equine,19,88,186,69,0,Val,0.822430,0.322430
53,24_EIPH_576255 Turnbull blue.svs,equine,520,2540,2802,635,3,Val,0.830065,0.330065
55,26_EIPH_566482 L Turnbull blue.svs,equine,142,717,1827,922,14,Val,0.834692,0.334692
43,11_EIPH_575697 Turnbull blue-002.svs,equine,49,250,688,99,0,Val,0.836120,0.336120
62,26_EIPH_566482 L Berliner Blau.svs,equine,323,1813,3666,2930,460,Val,0.848783,0.348783
51,21_EIPH_566482 R Turnbull blue.svs,equine,126,732,1021,157,0,Val,0.853147,0.353147
34,28_EIPH_569948 L berliner blau.svs,equine,964,113,10,0,0,Val,0.104921,0.395079

## Human

In [42]:
cat = data[data["Species"]=="Human"]
cat.sort_values(by=["mean_abs"])

,image_name,Species,0,1,2,3,4,Type,mean,mean_abs
12,10227_19 humane BAL Berliner Blau.svs,Human,1265,1943,324,5,0,Val,0.605673,0.105673
7,2702_20 BB Human BAL-001.svs,Human,963,523,413,67,2,Val,0.351952,0.148048
8,2707_20 TB BAL Human neu.svs,Human,1434,2954,1034,122,0,Val,0.673200,0.173200
18,11480_19 humane BAL Berliner Blau.svs,Human,391,1221,674,20,0,Val,0.757444,0.257444
13,10672_19 humane BAL Berliner Blau.svs,Human,12,75,451,612,79,Val,0.862069,0.362069
10,10080_19 humane BAL Berliner Blau-001.svs,Human,284,3015,2375,342,9,Val,0.913913,0.413913
9,10052_19 humane BAL Berliner Blau-001.svs,Human,120,1739,3744,739,9,Val,0.935449,0.435449
14,10672_19 humane BAL Turnbull Blau.svs,Human,3,59,419,321,59,Val,0.951613,0.451613
11,10120_19 humane BAL Berliner Blau.svs,Human,112,2225,4656,1502,105,Val,0.952075,0.452075
17,11323_19 humane BAL Berliner Blau.svs,Human,12,271,707,790,484,Val,0.957597,0.457597
16,10835_19 humane BAL Turnbull Blau.svs,Human,91,3729,6957,536,6,Val,0.976178,0.476178
15,10835_19 humane BAL Berliner Blau.svs,Human,39,2934,1569,34,0,Val,0.986882,0.486882

# Ablation Daten

In [45]:
data = data[data["image_name"].isin(cat_train+equine_train+human_train+cat_val+equine_val+human_val)]
data.sort_values(by=["Species", "mean_abs"])

,image_name,Species,0,1,2,3,4,Type,mean,mean_abs
3,BAL_Cat_Turnbull blue_10.svs,Cat,412,371,4,1,0,Val,0.473819,0.026181
4,BAL_Cat_Turnbull blue_12.svs,Cat,1897,1387,1,0,0,Val,0.422351,0.077649
0,BAL_Cat_Turnbull blue_1.svs,Cat,1200,2287,22,1,1,Val,0.655865,0.155865
2,BAL_Cat_Turnbull blue_6.svs,Cat,3009,895,0,0,0,Val,0.229252,0.270748
6,BAL_Cat_Turnbull blue_14.svs,Cat,2393,495,2,0,0,Val,0.171399,0.328601
5,BAL_Cat_Turnbull blue_13.svs,Cat,4663,810,2,0,0,Val,0.147999,0.352001
1,BAL_Cat_Turnbull blue_2.svs,Cat,57,502,10,0,0,Val,0.898032,0.398032
12,10227_19 humane BAL Berliner Blau.svs,Human,1265,1943,324,5,0,Val,0.605673,0.105673
7,2702_20 BB Human BAL-001.svs,Human,963,523,413,67,2,Val,0.351952,0.148048
8,2707_20 TB BAL Human neu.svs,Human,1434,2954,1034,122,0,Val,0.673200,0.173200
18,11480_19 humane BAL Berliner Blau.svs,Human,391,1221,674,20,0,Val,0.757444,0.257444
10,10080_19 humane BAL Berliner Blau-001.svs,Human,284,3015,2375,342,9,Val,0.913913,0.413913
9,10052_19 humane BAL Berliner Blau-001.svs,Human,120,1739,3744,739,9,Val,0.935449,0.435449
11,10120_19 humane BAL Berliner Blau.svs,Human,112,2225,4656,1502,105,Val,0.952075,0.452075
56,27_EIPH_571557 Turnbull blue.svs,equine,1392,1359,364,93,1,Val,0.494002,0.005998
27,17_EIPH_575796 Berliner Blau.svs,equine,2725,2625,715,166,14,Val,0.490654,0.009346
25,15_EIPH_568320 berliner blau.svs,equine,2884,3124,2138,733,12,Val,0.519973,0.019973
30,22_EIPH_575216 Berliner Blau.svs,equine,2147,2441,2025,899,69,Val,0.532040,0.032040
36,30_EIPH_588355 Berliner Blau.svs,equine,2815,2464,1523,606,26,Val,0.466755,0.033245
49,19_EIPH_566933 L Tunrbull blue.svs,equine,1197,1012,316,36,0,Val,0.458126,0.041874
38,02_EIPH_574162 Turnbull blue-001.svs,equine,2094,2560,1291,364,2,Val,0.550064,0.050064